/**
 * Древки Skylon — данные, не логика. Файл сгенерирован.
 *
 * Источник: сайт производителя, https://www.skylonarchery.com/ (раздел Arrows).
 * Пересборка: scripts/fetch-skylon-db.py — руками не правим, правки затрутся.
 *
 * Зачем отдельно от spineData.ts: та база собрана Stu Miller в 2012 году,
 * Skylon в ней нет вовсе. Формат записи тот же, чтобы списки просто складывались.
 *
 * Спайн Skylon публикует в дюймах — это и есть прогиб по ASTM (1.94 фунта на базе 28").
 * Диаметр переведён из миллиметров в дюймы.
 *
 * ВНИМАНИЕ: серии id 3.2 и id 4.2 — это трубки 5–6 мм по наружному диаметру,
 * то есть у нижней границы применимости модели Стю и за ней. См. README.
 */

import type { ShaftSpec } from './spineData'

export const SKYLON_SHAFTS: ShaftSpec[] = [
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "1100", "deflection": 1.1, "gpi": 4.64, "od": 0.20551, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "1000", "deflection": 1.0, "gpi": 4.9, "od": 0.20945, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "900", "deflection": 0.9, "gpi": 5.34, "od": 0.21102, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "850", "deflection": 0.85, "gpi": 5.48, "od": 0.21339, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "800", "deflection": 0.8, "gpi": 5.8, "od": 0.21575, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "750", "deflection": 0.75, "gpi": 5.94, "od": 0.21654, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "700", "deflection": 0.7, "gpi": 6.17, "od": 0.21969, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "650", "deflection": 0.65, "gpi": 6.42, "od": 0.22047, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "600", "deflection": 0.6, "gpi": 7.09, "od": 0.2248, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "550", "deflection": 0.55, "gpi": 7.47, "od": 0.22717, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "500", "deflection": 0.5, "gpi": 8.0, "od": 0.2315, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "450", "deflection": 0.45, "gpi": 8.63, "od": 0.23583, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Brixxon", "size": "400", "deflection": 0.4, "gpi": 9.47, "od": 0.24134, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "2000", "deflection": 2.0, "gpi": 3.6, "od": 0.19528, "focComp": 0, "stockLength": 26.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "1800", "deflection": 1.8, "gpi": 3.89, "od": 0.19685, "focComp": 0, "stockLength": 27.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "1500", "deflection": 1.5, "gpi": 4.0, "od": 0.19882, "focComp": 0, "stockLength": 28.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "1300", "deflection": 1.3, "gpi": 4.16, "od": 0.20394, "focComp": 0, "stockLength": 28.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "1100", "deflection": 1.1, "gpi": 4.64, "od": 0.20551, "focComp": 0, "stockLength": 28.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "1000", "deflection": 1.0, "gpi": 4.9, "od": 0.20945, "focComp": 0, "stockLength": 29.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "900", "deflection": 0.9, "gpi": 5.34, "od": 0.21102, "focComp": 0, "stockLength": 29.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "800", "deflection": 0.8, "gpi": 5.8, "od": 0.21575, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "700", "deflection": 0.7, "gpi": 6.17, "od": 0.21969, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Novice", "size": "600", "deflection": 0.6, "gpi": 7.09, "od": 0.2248, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "2000", "deflection": 2.0, "gpi": 3.6, "od": 0.19528, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "1800", "deflection": 1.8, "gpi": 3.89, "od": 0.19685, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "1500", "deflection": 1.5, "gpi": 4.0, "od": 0.19882, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "1300", "deflection": 1.3, "gpi": 4.16, "od": 0.20394, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "1100", "deflection": 1.1, "gpi": 4.64, "od": 0.20551, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "1000", "deflection": 1.0, "gpi": 4.9, "od": 0.20945, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "900", "deflection": 0.9, "gpi": 5.34, "od": 0.21102, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "850", "deflection": 0.85, "gpi": 5.48, "od": 0.21339, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "800", "deflection": 0.8, "gpi": 5.8, "od": 0.21575, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "750", "deflection": 0.75, "gpi": 5.94, "od": 0.21654, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "700", "deflection": 0.7, "gpi": 6.17, "od": 0.21969, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "650", "deflection": 0.65, "gpi": 6.42, "od": 0.22047, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "600", "deflection": 0.6, "gpi": 7.09, "od": 0.2248, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "550", "deflection": 0.55, "gpi": 7.47, "od": 0.22717, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "500", "deflection": 0.5, "gpi": 8.0, "od": 0.2315, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "450", "deflection": 0.45, "gpi": 8.63, "od": 0.23583, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Radius", "size": "400", "deflection": 0.4, "gpi": 9.47, "od": 0.24134, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "1000", "deflection": 1.0, "gpi": 4.7, "od": 0.1752, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "900", "deflection": 0.9, "gpi": 4.81, "od": 0.17717, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "850", "deflection": 0.85, "gpi": 4.94, "od": 0.17913, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "800", "deflection": 0.8, "gpi": 5.06, "od": 0.18071, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "750", "deflection": 0.75, "gpi": 5.31, "od": 0.18228, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "700", "deflection": 0.7, "gpi": 5.55, "od": 0.18386, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "650", "deflection": 0.65, "gpi": 5.83, "od": 0.18622, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "600", "deflection": 0.6, "gpi": 6.1, "od": 0.18819, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "550", "deflection": 0.55, "gpi": 6.5, "od": 0.19055, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "500", "deflection": 0.5, "gpi": 6.9, "od": 0.19291, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "450", "deflection": 0.45, "gpi": 7.42, "od": 0.19843, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "400", "deflection": 0.4, "gpi": 7.93, "od": 0.20354, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Paragon", "size": "350", "deflection": 0.35, "gpi": 8.47, "od": 0.20669, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "1000", "deflection": 1.0, "gpi": 4.7, "od": 0.1752, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "900", "deflection": 0.9, "gpi": 4.81, "od": 0.17717, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "850", "deflection": 0.85, "gpi": 4.94, "od": 0.17913, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "800", "deflection": 0.8, "gpi": 5.06, "od": 0.18071, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "750", "deflection": 0.75, "gpi": 5.31, "od": 0.18228, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "700", "deflection": 0.7, "gpi": 5.55, "od": 0.18386, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "650", "deflection": 0.65, "gpi": 5.83, "od": 0.18622, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "600", "deflection": 0.6, "gpi": 6.1, "od": 0.18819, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "550", "deflection": 0.55, "gpi": 6.5, "od": 0.19055, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "500", "deflection": 0.5, "gpi": 6.9, "od": 0.19291, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "450", "deflection": 0.45, "gpi": 7.42, "od": 0.19843, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "400", "deflection": 0.4, "gpi": 7.93, "od": 0.20354, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Performa", "size": "350", "deflection": 0.35, "gpi": 8.47, "od": 0.20669, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "1000", "deflection": 1.0, "gpi": 4.7, "od": 0.1752, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "900", "deflection": 0.9, "gpi": 4.81, "od": 0.17717, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "850", "deflection": 0.85, "gpi": 4.94, "od": 0.17913, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "800", "deflection": 0.8, "gpi": 5.06, "od": 0.18071, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "750", "deflection": 0.75, "gpi": 5.31, "od": 0.18228, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "700", "deflection": 0.7, "gpi": 5.55, "od": 0.18386, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "650", "deflection": 0.65, "gpi": 5.83, "od": 0.18622, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "600", "deflection": 0.6, "gpi": 6.1, "od": 0.18819, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "550", "deflection": 0.55, "gpi": 6.5, "od": 0.19055, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "500", "deflection": 0.5, "gpi": 6.9, "od": 0.19291, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "450", "deflection": 0.45, "gpi": 7.42, "od": 0.19843, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "400", "deflection": 0.4, "gpi": 7.93, "od": 0.20354, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Precium", "size": "350", "deflection": 0.35, "gpi": 8.47, "od": 0.20669, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Preminens", "size": "650", "deflection": 0.65, "gpi": 5.83, "od": 0.18622, "focComp": 0, "stockLength": 31.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Preminens", "size": "600", "deflection": 0.6, "gpi": 6.1, "od": 0.18819, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Preminens", "size": "550", "deflection": 0.55, "gpi": 6.5, "od": 0.19055, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Preminens", "size": "500", "deflection": 0.5, "gpi": 6.9, "od": 0.19291, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Preminens", "size": "450", "deflection": 0.45, "gpi": 7.42, "od": 0.19843, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Preminens", "size": "400", "deflection": 0.4, "gpi": 7.93, "od": 0.20354, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Preminens", "size": "350", "deflection": 0.35, "gpi": 8.47, "od": 0.20669, "focComp": 0, "stockLength": 32.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Backbone", "size": "700", "deflection": 0.7, "gpi": 6.7, "od": 0.25197, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Backbone", "size": "600", "deflection": 0.6, "gpi": 7.4, "od": 0.25906, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Backbone", "size": "500", "deflection": 0.5, "gpi": 7.9, "od": 0.26102, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Backbone", "size": "400", "deflection": 0.4, "gpi": 9.0, "od": 0.26732, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Backbone", "size": "350", "deflection": 0.35, "gpi": 9.9, "od": 0.27165, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Ebony", "size": "700", "deflection": 0.7, "gpi": 5.24, "od": 0.24449, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Ebony", "size": "600", "deflection": 0.6, "gpi": 6.19, "od": 0.25039, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Ebony", "size": "500", "deflection": 0.5, "gpi": 6.8, "od": 0.25433, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Ebony", "size": "400", "deflection": 0.4, "gpi": 8.16, "od": 0.26181, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Ebony", "size": "350", "deflection": 0.35, "gpi": 8.7, "od": 0.26496, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Instec", "size": "700", "deflection": 0.7, "gpi": 5.24, "od": 0.24449, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Instec", "size": "600", "deflection": 0.6, "gpi": 6.19, "od": 0.25039, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Instec", "size": "500", "deflection": 0.5, "gpi": 6.8, "od": 0.25433, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Instec", "size": "400", "deflection": 0.4, "gpi": 8.16, "od": 0.26181, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Instec", "size": "350", "deflection": 0.35, "gpi": 8.7, "od": 0.26496, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Instec", "size": "300", "deflection": 0.3, "gpi": 9.44, "od": 0.27126, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Quantic", "size": "700", "deflection": 0.7, "gpi": 6.69, "od": 0.25197, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Quantic", "size": "600", "deflection": 0.6, "gpi": 7.65, "od": 0.25906, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Quantic", "size": "500", "deflection": 0.5, "gpi": 8.03, "od": 0.26102, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Quantic", "size": "400", "deflection": 0.4, "gpi": 9.0, "od": 0.26732, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Quantic", "size": "350", "deflection": 0.35, "gpi": 9.89, "od": 0.27165, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Quantic", "size": "300", "deflection": 0.3, "gpi": 10.92, "od": 0.27874, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bentwood", "size": "800", "deflection": 0.8, "gpi": 5.4, "od": 0.27559, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bentwood", "size": "700", "deflection": 0.7, "gpi": 5.7, "od": 0.27953, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bentwood", "size": "600", "deflection": 0.6, "gpi": 5.87, "od": 0.28228, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bentwood", "size": "500", "deflection": 0.5, "gpi": 7.25, "od": 0.28976, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bentwood", "size": "400", "deflection": 0.4, "gpi": 7.73, "od": 0.29134, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bentwood", "size": "350", "deflection": 0.35, "gpi": 7.89, "od": 0.29252, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bentwood", "size": "300", "deflection": 0.3, "gpi": 9.68, "od": 0.30315, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Edge", "size": "800", "deflection": 0.8, "gpi": 4.2, "od": 0.26969, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Edge", "size": "700", "deflection": 0.7, "gpi": 5.12, "od": 0.27559, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Edge", "size": "600", "deflection": 0.6, "gpi": 5.58, "od": 0.27756, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Edge", "size": "500", "deflection": 0.5, "gpi": 5.8, "od": 0.28031, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Edge", "size": "400", "deflection": 0.4, "gpi": 7.33, "od": 0.28937, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Edge", "size": "350", "deflection": 0.35, "gpi": 7.61, "od": 0.29094, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Edge", "size": "300", "deflection": 0.3, "gpi": 8.5, "od": 0.29724, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Frontier", "size": "800", "deflection": 0.8, "gpi": 4.2, "od": 0.26969, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Frontier", "size": "700", "deflection": 0.7, "gpi": 5.12, "od": 0.27559, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Frontier", "size": "600", "deflection": 0.6, "gpi": 5.58, "od": 0.27756, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Frontier", "size": "500", "deflection": 0.5, "gpi": 5.8, "od": 0.28031, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Frontier", "size": "400", "deflection": 0.4, "gpi": 7.33, "od": 0.28937, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Frontier", "size": "350", "deflection": 0.35, "gpi": 7.61, "od": 0.29094, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Frontier", "size": "300", "deflection": 0.3, "gpi": 8.5, "od": 0.29724, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Maverick", "size": "500", "deflection": 0.5, "gpi": 7.7, "od": 0.29213, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Maverick", "size": "400", "deflection": 0.4, "gpi": 8.6, "od": 0.29724, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Maverick", "size": "350", "deflection": 0.35, "gpi": 9.4, "od": 0.30276, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Maverick", "size": "300", "deflection": 0.3, "gpi": 10.21, "od": 0.30551, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Phoric", "size": "700", "deflection": 0.7, "gpi": 5.4, "od": 0.27559, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Phoric", "size": "600", "deflection": 0.6, "gpi": 5.7, "od": 0.27756, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Phoric", "size": "500", "deflection": 0.5, "gpi": 6.0, "od": 0.28031, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Phoric", "size": "400", "deflection": 0.4, "gpi": 6.9, "od": 0.28937, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Phoric", "size": "350", "deflection": 0.35, "gpi": 7.4, "od": 0.29213, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Rove", "size": "500", "deflection": 0.5, "gpi": 7.25, "od": 0.28976, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Rove", "size": "400", "deflection": 0.4, "gpi": 7.73, "od": 0.29134, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Rove", "size": "350", "deflection": 0.35, "gpi": 7.89, "od": 0.29252, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Rove", "size": "300", "deflection": 0.3, "gpi": 9.68, "od": 0.30315, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Savage", "size": "500", "deflection": 0.5, "gpi": 6.5, "od": 0.28504, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Savage", "size": "400", "deflection": 0.4, "gpi": 7.4, "od": 0.28976, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Savage", "size": "350", "deflection": 0.35, "gpi": 7.9, "od": 0.29094, "focComp": 0, "stockLength": 30.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bruxx", "size": "500", "deflection": 0.5, "gpi": 6.61, "od": 0.34803, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bruxx", "size": "400", "deflection": 0.4, "gpi": 7.42, "od": 0.35236, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bruxx", "size": "350", "deflection": 0.35, "gpi": 7.92, "od": 0.35315, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Bruxx", "size": "300", "deflection": 0.3, "gpi": 8.52, "od": 0.35512, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Empros", "size": "500", "deflection": 0.5, "gpi": 7.27, "od": 0.35315, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Empros", "size": "400", "deflection": 0.4, "gpi": 8.49, "od": 0.35709, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Empros", "size": "350", "deflection": 0.35, "gpi": 8.69, "od": 0.35827, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Skylon", "series": "Empros", "size": "300", "deflection": 0.3, "gpi": 9.5, "od": 0.3622, "focComp": 0, "stockLength": 33.0, "insert": null, "insertGrains": null, "nock": null},
]
