/**
 * Древки Black Eagle — данные, не логика. Файл сгенерирован.
 *
 * Источник: сайт производителя, https://blackeaglearrows.com/
 * Пересборка: scripts/fetch-blackeagle-db.py — руками не правим, правки затрутся.
 *
 * Зачем отдельно от spineDataRetail.ts: карточки ритейлера по этой марке дают
 * спайн и GPI без наружного диаметра, и скрейпер их пропускает. Производитель
 * печатает полную таблицу, включая наружный диаметр.
 *
 * Формат записи тот же, чтобы списки просто складывались.
 */

import type { ShaftSpec } from './spineData'

export const BLACK_EAGLE_SHAFTS: ShaftSpec[] = [
  {"material": "carbon", "brand": "Black Eagle", "series": "Carnivore", "size": "250", "deflection": 0.25, "gpi": 9.7, "od": 0.303, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Carnivore", "size": "300", "deflection": 0.3, "gpi": 8.5, "od": 0.296, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Carnivore", "size": "350", "deflection": 0.35, "gpi": 7.5, "od": 0.291, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Carnivore", "size": "400", "deflection": 0.4, "gpi": 6.8, "od": 0.287, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Deep Impact", "size": "300", "deflection": 0.3, "gpi": 11.0, "od": 0.248, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Deep Impact", "size": "350", "deflection": 0.35, "gpi": 9.6, "od": 0.24, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Deep Impact", "size": "400", "deflection": 0.4, "gpi": 8.6, "od": 0.233, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Focus", "size": "250", "deflection": 0.25, "gpi": 10.5, "od": 0.245, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Focus", "size": "300", "deflection": 0.3, "gpi": 9.7, "od": 0.241, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Focus", "size": "350", "deflection": 0.35, "gpi": 8.2, "od": 0.23, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Focus", "size": "400", "deflection": 0.4, "gpi": 7.6, "od": 0.226, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "500", "deflection": 0.5, "gpi": 8.3, "od": 0.233, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "600", "deflection": 0.6, "gpi": 7.1, "od": 0.226, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "700", "deflection": 0.7, "gpi": 6.4, "od": 0.222, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "800", "deflection": 0.8, "gpi": 6.0, "od": 0.218, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "900", "deflection": 0.9, "gpi": 5.3, "od": 0.213, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "1000", "deflection": 1.0, "gpi": 5.1, "od": 0.212, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "1100", "deflection": 1.1, "gpi": 4.8, "od": 0.209, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "1200", "deflection": 1.2, "gpi": 5.1, "od": 0.211, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "1300", "deflection": 1.3, "gpi": 4.9, "od": 0.209, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Intrepid", "size": "1400", "deflection": 1.4, "gpi": 4.8, "od": 0.208, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Outlaw", "size": "300", "deflection": 0.3, "gpi": 9.1, "od": 0.3, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Outlaw", "size": "350", "deflection": 0.35, "gpi": 8.6, "od": 0.297, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Outlaw", "size": "400", "deflection": 0.4, "gpi": 8.1, "od": 0.294, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Outlaw", "size": "500", "deflection": 0.5, "gpi": 7.4, "od": 0.285, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Outlaw", "size": "600", "deflection": 0.6, "gpi": 6.8, "od": 0.278, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Outlaw", "size": "700", "deflection": 0.7, "gpi": 6.1, "od": 0.275, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS23", "size": "250", "deflection": 0.25, "gpi": 9.0, "od": 0.36, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS23", "size": "300", "deflection": 0.3, "gpi": 8.2, "od": 0.356, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS23", "size": "350", "deflection": 0.35, "gpi": 7.9, "od": 0.354, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS23", "size": "400", "deflection": 0.4, "gpi": 7.3, "od": 0.353, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS23", "size": "500", "deflection": 0.5, "gpi": 7.1, "od": 0.349, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS25", "size": "250", "deflection": 0.25, "gpi": 8.8, "od": 0.386, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS25", "size": "300", "deflection": 0.3, "gpi": 8.2, "od": 0.383, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS25", "size": "350", "deflection": 0.35, "gpi": 7.7, "od": 0.381, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS25", "size": "400", "deflection": 0.4, "gpi": 7.2, "od": 0.379, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS27 Super X", "size": "300", "deflection": 0.3, "gpi": 9.6, "od": 0.42, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "PS27 Super X", "size": "350", "deflection": 0.35, "gpi": 9.4, "od": 0.417, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Rampage .204", "size": "150", "deflection": 0.15, "gpi": 16.0, "od": 0.307, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Rampage .204", "size": "200", "deflection": 0.2, "gpi": 12.8, "od": 0.285, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Rampage .204", "size": "250", "deflection": 0.25, "gpi": 10.7, "od": 0.276, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Rampage .204", "size": "300", "deflection": 0.3, "gpi": 8.7, "od": 0.264, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Rampage .204", "size": "350", "deflection": 0.35, "gpi": 8.2, "od": 0.261, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Rampage .204", "size": "400", "deflection": 0.4, "gpi": 7.0, "od": 0.253, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Renegade", "size": "250", "deflection": 0.25, "gpi": 10.8, "od": 0.28, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Renegade", "size": "300", "deflection": 0.3, "gpi": 10.0, "od": 0.275, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Renegade", "size": "350", "deflection": 0.35, "gpi": 8.7, "od": 0.267, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Renegade", "size": "400", "deflection": 0.4, "gpi": 8.0, "od": 0.263, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "300", "deflection": 0.3, "gpi": 10.2, "od": 0.218, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "350", "deflection": 0.35, "gpi": 9.0, "od": 0.212, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "400", "deflection": 0.4, "gpi": 8.1, "od": 0.208, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "450", "deflection": 0.45, "gpi": 7.5, "od": 0.201, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "500", "deflection": 0.5, "gpi": 7.0, "od": 0.198, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "550", "deflection": 0.55, "gpi": 6.5, "od": 0.193, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "600", "deflection": 0.6, "gpi": 6.3, "od": 0.191, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "650", "deflection": 0.65, "gpi": 6.0, "od": 0.189, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "700", "deflection": 0.7, "gpi": 5.8, "od": 0.186, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "750", "deflection": 0.75, "gpi": 5.6, "od": 0.185, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Revelation 3:20", "size": "800", "deflection": 0.8, "gpi": 5.3, "od": 0.183, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Spartan", "size": "200", "deflection": 0.2, "gpi": 11.6, "od": 0.297, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Spartan", "size": "250", "deflection": 0.25, "gpi": 10.0, "od": 0.289, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Spartan", "size": "300", "deflection": 0.3, "gpi": 9.0, "od": 0.282, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Spartan", "size": "350", "deflection": 0.35, "gpi": 8.0, "od": 0.276, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Spartan", "size": "400", "deflection": 0.4, "gpi": 7.2, "od": 0.272, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Talon", "size": "300", "deflection": 0.3, "gpi": 9.3, "od": 0.298, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Talon", "size": "350", "deflection": 0.35, "gpi": 8.1, "od": 0.293, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Talon", "size": "400", "deflection": 0.4, "gpi": 7.6, "od": 0.291, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Talon", "size": "500", "deflection": 0.5, "gpi": 6.8, "od": 0.286, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Vintage", "size": "350", "deflection": 0.35, "gpi": 9.8, "od": 0.303, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Vintage", "size": "400", "deflection": 0.4, "gpi": 9.2, "od": 0.301, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Vintage", "size": "500", "deflection": 0.5, "gpi": 8.5, "od": 0.297, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "Vintage", "size": "600", "deflection": 0.6, "gpi": 7.9, "od": 0.293, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "X-Impact", "size": "200", "deflection": 0.2, "gpi": 11.0, "od": 0.256, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "X-Impact", "size": "250", "deflection": 0.25, "gpi": 9.5, "od": 0.24, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "X-Impact", "size": "300", "deflection": 0.3, "gpi": 8.1, "od": 0.231, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "X-Impact", "size": "350", "deflection": 0.35, "gpi": 7.4, "od": 0.228, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "X-Impact", "size": "400", "deflection": 0.4, "gpi": 6.7, "od": 0.221, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
  {"material": "carbon", "brand": "Black Eagle", "series": "X-Impact", "size": "500", "deflection": 0.5, "gpi": 5.8, "od": 0.214, "focComp": 0, "stockLength": null, "insert": null, "insertGrains": null, "nock": null},
]
